# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eed5f7247934bb953a508923ba99e87a0ddbf9d6048e4a98b515b7fd414486b2d7eb0c36b1434f87fbc7f2c7b4ac5b6f006eea55c614035e1e8bc7f99328d0f

test:
  secret_key_base: 93de5910a8249785df792dfefe246324310627136383de11d33a157fe8d5b60fd27b1f095da7c6787f78387a51c2c911b5bb3d60cc5d2251b749fb9808fefd1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
